import os

PROJECT_ID = os.environ["PROJECT_ID"]
REGION = os.environ["REGION"]

DATA_STORE_ID = os.environ["DATA_STORE_ID"] 
DATA_STORE_LOCATION = os.environ["DATA_STORE_LOCATION"]

TOPIC_DOCUMENT_PROCESSOR = os.environ.get("TOPIC_DOCUMENT_PROCESSOR", "")

DOCUMENT_BUCKET =  os.environ.get("DOCUMENT_BUCKET", "")

DEFAULT_SUB_FOLDERS = ""