# Generated by Django 5.1.6 on 2025-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="uuid",
            field=models.CharField(default="", max_length=200),
        ),
    ]
